### ISSUE TITLE
Gerar JSONs com totalizações para cada nível em um dado ano.

### ISSUE THREAD

**Issue by andresmrm** [okfn-brasil/gastos_abertos#117]

**Comment by andresmrm** [comment]
Comecei:
https://github.com/okfn-brasil/gastos_abertos/blob/master/utils/generate_total_json.py

**Comment by andresmrm** [comment]
Básico funcionando e minimamente testado manualmente com o site da prefeitura.
https://github.com/okfn-brasil/gastos_abertos/pull/119

**Comment by aivuk** [comment]
O formato do JSON já deve ser no formato esperado pelo HighCharts. Os valores que aparecem no JSON são apenas dos níveis inferiores e a estrutura deverá ser aprofundada por nível.

**Comment by andresmrm** [comment]
Acho que agora foi:
https://github.com/okfn-brasil/gastos_abertos/pull/123
Achei um exemplo próximo do que precisávamos e dai sim consegui entender como o JSON tinha que ficar.
EDIT: o exemplo foi esse: http://jsfiddle.net/6LXVQ/2/
