### ISSUE TITLE
Usar novos JSONs com totalizações no Drilldown

### ISSUE THREAD

**Issue by andresmrm** [okfn-brasil/gastos_abertos#121]
Usar os JSONs daqui:
https://github.com/okfn-brasil/gastos_abertos/issues/117
Para o drilldown em Highcharts.

**Comment by andresmrm** [comment]
Acho que foi:
https://github.com/okfn-brasil/gastos_abertos_website/pull/32
Dá para escolher ano via URL e o level tb. Ex.:
http://127.0.0.1:8000/receitas/?year=2013&level=9

Algumas questões:
- Usar cores diferentes para as barras? Isso significaria ter uma legenda embaixo para cada cor, ou desativar a legenda. Só que sem legenda não dá para filtrar quais barras ele vai mostrar...
- Estão faltando várias descrições de códigos no nosso BD. Principalmente para as deduções (de começo 9) (talvez seja só pegar a descrição do código sem o 9 e colocar "Dedução" na frente..)
- Quando escolhe o level não está subindo para os acima do level inicial...
- Falta arrumar a legenda para não estar me G/M

**Comment by aivuk** [comment]
Oi Andres,

duas coisas:
1. É importante que antes que a tarefa seha fechada, que o resultado dela esteja disponível em http://site.gastosabertos.org, caso contrário não feche-a.
2. Lembra-se que comentei que as legendas estavam erradas? Pois é, arrumar o json incluia arrumar isso. Precisamos ter a opção de desabilitar cada barra individual do gráfico, mas a única forma que vi para fazer isso é criando múltiplas séries temporais. A forma que eu fiz está ERRADA, então precisamos descobrir como conseguimos: a) ter barras com legendas corretas; b) ter barras que podem ser desabilitadas como está atualmente no primeiro nível.

Enquanto estes dois ítens não estiverem fechados, deixamos o issue como open. Você pode criar outras issues se quiser quebrar essa tarefa em mais ítens, mas essa issua permanece aberta até os ítens acima serem resolvidos, ok?

**Comment by andresmrm** [comment]
Ok, vou ver isso.
Sobre 1, ele não parece estar usando o meu JS no servidor... Está fazendo o deploy automático?
Sobre 2, acho que sei o que tem que fazer. Vendo...

**Comment by andresmrm** [comment]
É, pelo visto ainda não implementaram isso:
http://forum.highcharts.com/highcharts-usage/how-to-pass-multiple-series-to-drilldown-t31322/
E se formos mesmo fazer isso vamos precisar fazer na mão...
Tentei adicionar as séries na mão, mas está concorrendo com o drilldown dele e as vezes consegue, as vezes não.
https://github.com/okfn-brasil/gastos_abertos_website/pull/33
Acho que teria que deixar tudo manual...

**Comment by aivuk** [comment]
Sim Andres, pelo que entendi da sugestão no link, é desabilitar o drilldown e utilizar apenas o addSeries e remove series.

**Comment by andresmrm** [comment]
Here we go...

Quoting Edgar Z. Alvarenga (2015-02-28 08:15:41)

**Comment by andresmrm** [comment]
Descendo na mão agora. Parece que está indo bem.
Mas falta poder subir.

**Comment by andresmrm** [comment]
Adicionei um botão para poder subir:
https://github.com/okfn-brasil/gastos_abertos_website/pull/35
Ainda precisa tratar quando não dá para descer mais.

**Comment by LuizArmesto** [comment]
@andresmrm qual o estado dessa issue? pode fechar?

**Comment by andresmrm** [comment]
Pelo que estou vendo aqui sim. Ele está usando esse link para carregar as totalizações:
http://demo.gastosabertos.org/receita/static/total_by_year_by_code/2014.json
Que aparentemente era o objetivo principal da issue.
