### ISSUE TITLE
Simplificar códigos usados como chave única na execução

### ISSUE THREAD

**Issue by andresmrm** [okfn-brasil/gastos_abertos#182]
O códigos gerados [aqui](https://github.com/okfn-brasil/gastos_abertos/blob/master/utils/import_execucao.py#L57-L59) as vezes tem números sem significados ou repetidos:
`2015.0.2015.0.93.0.10.0.8.0.241.0.3007.0.44505200.0.50.0.52.0.0.0.1774.0`
Ver se consegue reduzí-los. Mais especificamente, tirar esses `0`s que aparecem no ano de 2015, e possivelmente um dos dois `2015`.

**Comment by aivuk** [comment]
Descreva melhor o ticket.  O que exatamente está se referindo (quais arquivos, linhas, funcionalidade descrita no wiki ou outro local, etc)?

**Comment by andresmrm** [comment]
Feito. =)
