### ISSUE TITLE
Endpoint para retornar últimas atualizações dos dados de execução

### ISSUE THREAD

**Issue by andresmrm** [okfn-brasil/gastos_abertos#195]
Relacionado a:
https://github.com/okfn-brasil/cuidando2/issues/88

Ex.: Me retorne todas as atualizações nos dados nos últimos 10 dias.

**Comment by andresmrm** [comment]
Se formos mesmo disponibilizar em RSS, podemos usar uma lib como essa:
https://github.com/lkiesow/python-feedgen

Mas fiquei na dúvida se faz sentindo para esse caso... são muitas atualizações, +500 linhas/dia. =/

**Comment by LuizArmesto** [comment]
Com um volume tão grande de atualizações eu não vejo um caso de uso para RSS
