### ISSUE TITLE
Criar linha de comando para iniciar importação dos dados da Receita

### ISSUE THREAD

**Issue by aivuk** [okfn-brasil/gastos_abertos#20]

**Comment by aivuk** [comment]
Done but need to run from utils/ directory like:

$ cd utils
$ python import_revenue.py

**Comment by andresmrm** [comment]
Estou tendo esse [erro](https://gist.github.com/andresmrm/8e8c1ee46c6946911d32) quando rodo os dois comandos que você passou. =/

Outra coisa, o tratamento do `code` aqui não deveria ser igual ao que eu fiz no outro script? Não seria bom colocar esse trecho de código em um arquivo a parte para ser reutilizado pelos dois scripts?

**Comment by aivuk** [comment]
Eu acho uma boa salvar na inserção o código como veio do CSV original, se for para ter alguma alteração fazer isso em colunas extras.

Quanto ao seu erro, me passe o arquivo que está inserindo. Estou utilizando o  data/receitas_min.csv pra inserção.

**Comment by andresmrm** [comment]
Quoting aivuk (2015-02-06 11:02:16)

> Eu acho uma boa salvar na inserção o código como veio do CSV original, se for
> para ter alguma alteração fazer isso em colunas extras.
> Ah, entendi, ok.
> 
> Quanto ao seu erro, me passe o arquivo que está inserindo. Estou utilizando o
> data/receitas_min.csv pra inserção.
> Eu tb. O script escolhe esse arquivo automaticamente:

```
data = pd.read_csv('../data/receitas_min.csv', encoding='utf8')
```

**Comment by aivuk** [comment]
Zere seu db e crie um novo. Quais versões do Pandas e SQLAlchemy? Isso funcionou no servidor do gastos abertos e em dois outros computadores diferentes que testei, o problema deve estar no seu lado.

**Comment by andresmrm** [comment]
Dei:

```
rm /tmp/db.sqlite
python manage.py initdb
```

Mas o erro persiste.

pandas-0.15.2-py2.7
SQLAlchemy-0.9.8-py2.7

Quoting aivuk (2015-02-06 12:26:28)

**Comment by andresmrm** [comment]
Alterando a função de inserção para:

def insert_rows(rows_data):
    for r in rows_data:
        ins = insert(Revenue.**table**, r)
        db.session.execute(ins)
        db.session.commit()

Não dá erro, mas ficou mais de um minuto inserindo dados, então matei o
processo com medo do que ele estava fazendo...

Quoting Andres MRM (2015-02-06 13:02:54)

**Comment by andresmrm** [comment]
Sei que vai soar estranho, mas ele dá pau para qualquer valor maior que 90 nessa linha:
https://github.com/okfn-brasil/gastos_abertos/blob/master/utils/import_revenue.py#L40

**Comment by aivuk** [comment]
qual versão do sqlite3 pu pysqlite2? 

teste num banco de dados mysql também.

**Comment by andresmrm** [comment]
SQLite version 3.8.8.2 2015-01-30 14:30:45
pudb-2015.1-py2.7

pysqlite2 não estou achando... nem com pip show.

Quoting aivuk (2015-02-06 21:41:40)

**Comment by aivuk** [comment]
queria saber a versão do slite3 pro python na verdade.

contando o número de values e entradas no insert gerado está tudo ok.

**Comment by aivuk** [comment]
> Sei que vai soar estranho, mas ele dá pau para qualquer valor maior que 90 nessa linha

Você diz o número de linhas pra inserir por vez? Essa linha é onde define-se que quero inserir 100 linhas por vez. Não está com problema de memória não?

**Comment by andresmrm** [comment]
Sim, eu entendi o que faz a linha. Por isso que é tão estranho.
Memória? Vc diz RAM?

```
          total        used        free      shared  buff/cache   available
```

Mem:           7,7G        1,2G        4,9G        201M        1,6G        6,0G

Como vejo o sqlite3 para o Python?

Quoting aivuk (2015-02-06 22:02:24)
