### ISSUE TITLE
Implementar na API da busca dos contratos retorno de trecho do texto que deu o match

### ISSUE THREAD

**Issue by aivuk** [okfn-brasil/gastos_abertos#216]
O Elasticsearch retorna mais de um trecho? Se sim, retornar sempre o mais relevante.

**Comment by LuizArmesto** [comment]
É configurável quantos trechos ele retorna no máximo e o tamanho deles. Sei que na API do ES tem uma opção para ele ordenar os trecho pelo mais relevante, mas não sei como configurar no na biblioteca do python. Por enquanto eu mandei retornar no máximo 3 trechos de 400 caracteres e estou concatenando-os com '...' entre eles. Se sobrar tempo depois eu vejo direito como pegar só o mais relevante.

Se a linha com o trecho do conteúdo aparecer logo abaixo da linha do objeto (antes da linha com as demais info) é só limpar o cache. O lugar correto da linha é no fim.

Na chamada da API ele só acrescenta esse trecho, assim como as tags nos outros campos, se o argumento highlight=true for passado (deixei o padrão para false)

Coloquei no link da linha do objeto a url para o arquivo txt e debaixo do id o link para o arquivo original (download)
