### ISSUE TITLE
Expansão de Contratos para Acompanhamento de Editais

### ISSUE THREAD

**Issue by carlosandrade** [okfn-brasil/gastos_abertos#223]
Alguém sabe a relação [desse sistema do município de SP](http://e-negocioscidadesp.prefeitura.sp.gov.br/DetalheLicitacao.aspx?l=Vl56%2b6TRDk8%3d) com o que [usamos atualmente de contratos](http://transparencia.prefeitura.sp.gov.br/contas/Paginas/Contratos-v2.aspx)? 

Achei interessante que dava para ver detalhado todas as fazes do edital e para alguns até os lances de licitação. O código parecia ser do mesmo tipo para cruzar com o que a gente tem, mas usando [as buscas do nosso site](http://site.gastosabertos.org/contratos) não consegui cruzar nenhum.

**Comment by aivuk** [comment]
Ops, fechei sem querer antes de comentar. Essa base possui informações muito interessantes do processo prévio ao fechamento de um contrato com a Prefeitura. Mas não verifiquei ainda se existe pra cada um dos nossos contratos uma entrada nesse sistema.  Num primeiro momento, essa base entra em nossas documentações, no nosso Wiki para não perdermos de vista. Podemos também referenciar essa página na futura página do site que descreverá o que é a sessão Contratos do gastosabertos.org.
