### ISSUE TITLE
Criar modelos de dados para codigos da Receita

### ISSUE THREAD

**Issue by aivuk** [okfn-brasil/gastos_abertos#49]
Criar modelo de dados do SQLAlchemy em:

https://github.com/okfn-brasil/gastos_abertos/blob/master/gastosabertos/receita/models.py

O moledo contera tres campos:

Id : chave primaria

code: string => A ideia e que coletemos os  codigos do arquivo:

https://github.com/okfn-brasil/gastos_abertos_dados/blob/master/doc/Codificacao_de_Receitas_2013.txt 

ignorando os zeros nao significativos a direita. Por exemplo, em "Impostos" guardariamos o codigo "111" e Taxas "112".

description: string

**Comment by andresmrm** [comment]
qual é para ser mesmo o nome da nova tabela/class?

**Comment by andresmrm** [comment]
Isso?

https://github.com/okfn-brasil/gastos_abertos/commit/7daa2672a954ce599039adda53da4bc614da117e

**Comment by andresmrm** [comment]
Mudei a PK para ser o código:
https://github.com/okfn-brasil/gastos_abertos/commit/e8c59965590a690bec95452c3e8b951f1eb87631
Está certo? Pode fechar?

**Comment by andresmrm** [comment]
@aivuk ?

**Comment by aivuk** [comment]
Não acho que seja uma boa atrelar o PK ao código, a não ser que crie uma nova coluna que é o código no formato original sem nenhuma modificação nossa. Isso porque estamos ainda mudando com frequência o padrão utilizado pra salvar os codes.

**Comment by andresmrm** [comment]
Ok, desfeito.

Quoting aivuk (2015-02-06 12:29:35)
