### ISSUE TITLE
Documentar API para obter nomes e códigos da Receita

### ISSUE THREAD

**Issue by aivuk** [okfn-brasil/gastos_abertos#53]
https://github.com/okfn-brasil/gastos_abertos/wiki/API

**Comment by andresmrm** [comment]
https://github.com/okfn-brasil/gastos_abertos/wiki/API#revenues-codes-descriptions
Isso?

**Comment by andresmrm** [comment]
@aivuk ?
(Você quer eu continue te chamando para validar o que eu fiz ou só feche os issues e pronto?)

**Comment by aivuk** [comment]
Pode fechar, se tiver problem eu reabro, melhor.
