### ISSUE TITLE
Add 'importdata' command to fabfile.py

### ISSUE THREAD

**Issue by andresmrm** [okfn-brasil/gastos_abertos#87]
Adicionar um comando ao fabfile para importar dados no BD.

**Comment by andresmrm** [comment]
@aivuk era algo assim que você estava pensando?
https://github.com/andresmrm/gastos_abertos/commit/84a0d11643bd917403992aebb91c5af89a3302dd
É para ter um "importdata_server" para ser rodado no servidor e um "importdata_local" para a máquina local? Pelo que eu vi ele não detecta onde está rodando para saber o que rodar...

**Comment by aivuk** [comment]
pode criar um remoto, ou melhor, parametrizar isso neste task.
