### ISSUE TITLE
Qual formato usaremos para datas?

### ISSUE THREAD

**Issue by andresmrm** [okfn-brasil/gastos_abertos#97]
JSON Schema já vem com um formato predefinido para datas que parece ser um padrão forte:
http://tools.ietf.org/html/rfc3339
Ex.:
1985-04-12T23:20:50.52Z
1996-12-19T16:39:57-08:00
1937-01-01T12:00:27.87+00:20

Passamos a usar esse ou continuamos no "2010-02-28"? Não é difícil colocar no Schema esse "nosso padrão" também.

**Comment by aivuk** [comment]
Podemos utilizar o rfc3339. A lib que utilizamos suporta isso:

http://flask-restful.readthedocs.org/en/latest/fields.html

Corrigindo, não sei se suporta diretamente, pois diz que suporta o padrão ISO 8601 e o rfc3339 é uma versão mais estrita dele.

**Comment by andresmrm** [comment]
Usando ISO8601 vem assim:
"2010-01-31T00:00:00+00:00"
Parece bom para mim...
Mas tem que alterar o BD de:
date = Column(db.Date())
para:
date = Column(db.DateTime())
Faço o patch?

**Comment by aivuk** [comment]
Pode fazer

**Comment by andresmrm** [comment]
Como recrio o BD no servidor?

```
fab reset; fab initdb; fab importdata:remote
```

Não vai funcionar, né?

**Comment by aivuk** [comment]
Não vai não, tem que fazer um initdb remoto e reset também. E adicionar sua chave de ssh pro user gastosabertos. Entendeu?

**Comment by andresmrm** [comment]
Deu certo! Vlw!
